version: "3.8"

services:
  # PostgreSQL Database
  db-postgres:
    image: postgres:13
    container_name: cursos-microservice-db
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    networks:
      - angular-spring-microservices
    volumes:
      - ./DockerPostgre/Data:/var/lib/postgresql/data

  # MySQL Database
  db-mysql:
    image: mysql:8
    container_name: usuario-microservice-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: appdb
    networks:
      - angular-spring-microservices
    volumes:
      - ./DockerMysql/Data/usuarios:/var/lib/mysql

  # First microservice using MySQL
  msvc-usuarios:
    image: beemila666/usuario-microservice:latest
    container_name: usuario-microservice
    restart: always
    environment:
      DB_NAME: appdb
      DB_USER: root
      DB_PASS: 12345
      APP_PORT: 8001
      KEYCLOAK_HOST: http://keycloak-service
    ports:
      - "8001:8001"
    depends_on:
      - db-mysql
      - keycloak-service
    networks:
      - angular-spring-microservices

  # Second microservice using PostgreSQL
  msvc-cursos:
    image: beemila666/curso-microservice:latest
    container_name: cursos-microservice
    restart: always
    environment:
      DB_NAME: appdb
      DB_USER: postgres
      DB_PASS: 12345
      APP_PORT: 8002
      KEYCLOAK_HOST: http://keycloak-service
    ports:
      - "8002:8002"
    depends_on:
      - db-postgres
      - keycloak-service
    networks:
      - angular-spring-microservices

  # Angular front-end
  angular-app:
    image: beemila666/front-microservice:latest
    container_name: angular-app
    restart: always
    ports:
      - "4200:80"
    networks:
      - angular-spring-microservices

  # Keycloak service
  keycloak-service:
    container_name: keycloak-service
    hostname: keycloak-service
    image: quay.io/keycloak/keycloak:21.0.1
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./DockerKeyloack/keycloak_data:/opt/keycloak/data
    command:
      - start-dev
    networks:
      - angular-spring-microservices

networks:
  angular-spring-microservices:
    driver: bridge
